name: rearrangement_GIT
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - alsa-lib=1.2.3=h516909a_0
  - anyio=3.3.0=py36h5fab9bb_0
  - argon2-cffi=20.1.0=py36h8f6f2f9_2
  - async_generator=1.10=py_0
  - attrs=21.2.0=pyhd8ed1ab_0
  - autograd=1.3=py_0
  - babel=2.9.1=pyh44b312d_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - bleach=4.1.0=pyhd8ed1ab_0
  - brotlipy=0.7.0=py36h8f6f2f9_1001
  - ca-certificates=2021.5.30=ha878542_0
  - certifi=2021.5.30=py36h5fab9bb_0
  - cffi=1.14.6=py36hd8eec40_1
  - chardet=4.0.0=py36h5fab9bb_1
  - charset-normalizer=2.0.0=pyhd8ed1ab_0
  - contextvars=2.4=py_0
  - cryptography=3.4.7=py36hb60f036_0
  - cvxopt=1.2.7=py36hbc9fb32_0
  - cycler=0.10.0=py_2
  - dataclasses=0.8=pyh787bdff_2
  - dbus=1.13.6=h48d8840_2
  - decorator=5.1.0=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - dsdp=5.8=hd9d9efa_1203
  - entrypoints=0.3=pyhd8ed1ab_1003
  - expat=2.4.1=h9c3ff4c_0
  - fftw=3.3.10=nompi_hcdd671c_100
  - fontconfig=2.13.1=hba837de_1005
  - freetype=2.10.4=h0708190_1
  - future=0.18.2=py36h5fab9bb_3
  - gettext=0.19.8.1=h73d1719_1006
  - glib=2.68.4=h9c3ff4c_1
  - glib-tools=2.68.4=h9c3ff4c_1
  - glpk=4.65=h9202a9a_1004
  - gmp=6.2.1=h58526e2_0
  - gmpy2=2.1.0b5=py36h3f4d9dc_0
  - gsl=2.7=he838d99_0
  - gst-plugins-base=1.18.5=hf529b03_0
  - gstreamer=1.18.5=h76c114f_0
  - icu=68.1=h58526e2_0
  - idna=3.1=pyhd3deb0d_0
  - immutables=0.16=py36h8f6f2f9_0
  - importlib-metadata=4.8.1=py36h5fab9bb_0
  - ipykernel=5.5.5=py36hcb3619a_0
  - ipython=7.16.1=py36he448a4c_2
  - ipython_genutils=0.2.0=py_1
  - jbig=2.1=h7f98852_2003
  - jedi=0.17.2=py36h5fab9bb_1
  - jinja2=3.0.1=pyhd8ed1ab_0
  - jpeg=9d=h36c2ea0_0
  - json5=0.9.5=pyh9f0ad1d_0
  - jsonschema=3.2.0=pyhd8ed1ab_3
  - jupyter_client=7.0.3=pyhd8ed1ab_0
  - jupyter_core=4.8.1=py36h5fab9bb_0
  - jupyter_server=1.11.0=pyhd8ed1ab_0
  - jupyterlab=3.1.12=pyhd8ed1ab_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_server=2.8.1=pyhd8ed1ab_0
  - kiwisolver=1.3.1=py36h605e78d_1
  - krb5=1.19.2=hcc1bbae_0
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=2.2.1=h9c3ff4c_0
  - libblas=3.9.0=11_linux64_mkl
  - libcblas=3.9.0=11_linux64_mkl
  - libclang=11.1.0=default_ha53f305_1
  - libdeflate=1.7=h7f98852_5
  - libedit=3.1.20191231=he28a2e2_2
  - libevent=2.1.10=hcdb4288_3
  - libffi=3.4.2=h9c3ff4c_2
  - libgcc-ng=11.2.0=h1d223b6_8
  - libgfortran-ng=11.2.0=h69a702a_8
  - libgfortran5=11.2.0=h5c6108e_8
  - libglib=2.68.4=h174f98d_1
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=11_linux64_mkl
  - libllvm11=11.1.0=hf817b99_2
  - libogg=1.3.4=h7f98852_1
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.37=h21135ba_2
  - libpq=13.3=hd57d9b9_0
  - libprotobuf=3.16.0=h780b84a_0
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=11.2.0=he4da1e4_8
  - libtiff=4.3.0=hf544144_1
  - libuuid=2.32.1=h7f98852_1000
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp-base=1.2.1=h7f98852_0
  - libxcb=1.13=h7f98852_1003
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.12=h72842e0_0
  - llvm-openmp=12.0.1=h4bd325d_1
  - lz4-c=1.9.3=h9c3ff4c_1
  - markupsafe=2.0.1=py36h8f6f2f9_0
  - matplotlib=3.3.4=py36h5fab9bb_0
  - matplotlib-base=3.3.4=py36hd391965_0
  - metis=5.1.0=h58526e2_1006
  - mistune=0.8.4=py36h8f6f2f9_1004
  - mkl=2021.3.0=h726a3e6_557
  - mpc=1.2.1=h9f54685_0
  - mpfr=4.1.0=h9202a9a_1
  - mpmath=1.2.1=pyhd8ed1ab_0
  - mysql-common=8.0.25=ha770c72_2
  - mysql-libs=8.0.25=hfa10184_2
  - nbclassic=0.3.2=pyhd8ed1ab_0
  - nbclient=0.5.4=pyhd8ed1ab_0
  - nbconvert=6.0.7=py36h5fab9bb_3
  - nbformat=5.1.3=pyhd8ed1ab_0
  - ncurses=6.2=h58526e2_4
  - nest-asyncio=1.5.1=pyhd8ed1ab_0
  - ninja=1.10.2=h4bd325d_0
  - notebook=6.3.0=py36h5fab9bb_0
  - nspr=4.30=h9c3ff4c_0
  - nss=3.69=hb5efdd6_0
  - numpy=1.19.5=py36hfc0c790_2
  - olefile=0.46=pyh9f0ad1d_1
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1l=h7f98852_0
  - packaging=21.0=pyhd8ed1ab_0
  - pandoc=2.14.2=h7f98852_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.7.1=pyh9f0ad1d_0
  - pcre=8.45=h9c3ff4c_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=8.3.2=py36h676a545_0
  - pip=21.2.4=pyhd8ed1ab_0
  - prometheus_client=0.11.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.20=pyha770c72_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.10.0=pyhd8ed1ab_0
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.12.3=py36h5fab9bb_7
  - pyqt-impl=5.12.3=py36h7ec31b9_7
  - pyqt5-sip=4.19.18=py36hc4f0c31_7
  - pyqtchart=5.12=py36h7ec31b9_7
  - pyqtwebengine=5.12.1=py36h7ec31b9_7
  - pyrsistent=0.17.3=py36h8f6f2f9_2
  - pysocks=1.7.1=py36h5fab9bb_3
  - python=3.6.13=hb7a2778_1_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.6=2_cp36m
  - pytorch=1.9.0=cpu_py36h1c7b8ea_2
  - pytorch-cpu=1.9.0=cpu_py36h718b53a_2
  - pytz=2021.1=pyhd8ed1ab_0
  - pyzmq=22.3.0=py36h7068817_0
  - qt=5.12.9=hda022c4_4
  - readline=8.1=h46c0cb4_0
  - requests=2.26.0=pyhd8ed1ab_0
  - requests-unixsocket=0.2.0=py_0
  - scipy=1.5.3=py36h81d768a_1
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=58.0.4=py36h5fab9bb_1
  - six=1.16.0=pyh6c4a22f_0
  - sleef=3.5.1=h7f98852_1
  - sniffio=1.2.0=py36h5fab9bb_1
  - sqlite=3.36.0=h9cd32fc_1
  - suitesparse=5.10.1=h9e50725_1
  - sympy=1.8=py36h5fab9bb_0
  - tbb=2021.3.0=h4bd325d_0
  - terminado=0.12.1=py36h5fab9bb_0
  - testpath=0.5.0=pyhd8ed1ab_0
  - tk=8.6.11=h27826a3_1
  - tornado=6.1=py36h8f6f2f9_1
  - traitlets=4.3.3=pyhd8ed1ab_2
  - typing-extensions=3.10.0.0=hd8ed1ab_0
  - typing_extensions=3.10.0.0=pyha770c72_0
  - urllib3=1.26.6=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - websocket-client=0.57.0=py36h5fab9bb_4
  - wheel=0.37.0=pyhd8ed1ab_1
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.2.5=h516909a_1
  - zeromq=4.3.4=h9c3ff4c_1
  - zipp=3.5.0=pyhd8ed1ab_0
  - zlib=1.2.11=h516909a_1010
  - zstd=1.5.0=ha95c52a_0
  - pip:
    - ansitable==0.9.6
    - colored==1.4.2
    - pgraph-python==0.6.1
    - progress==1.6
    - qpsolvers==1.7.0
    - quadprog==0.1.9
    - roboticstoolbox-python==0.11.0
    - rtb-data==0.10.1
    - spatialgeometry==0.2.0
    - spatialmath-python==0.11
    - sphinxcontrib-jsmath==1.0.1
    - swift-sim==0.10.0
    - websockets==9.1
prefix: /home/prajwal/miniconda3/envs/rearrangement_GIT
